tap "git-duet/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "minifast/setup", "git@github.com:minifast/homebrew-setup.git"

brew "ack"
brew "asdf"
brew "awscli"
brew "htop"
brew "nvm"
brew "postgresql@14", restart_service: true
brew "rbenv"
brew "rbenv-gemset"
brew "redis", restart_service: true
brew "starship"
brew "vips"
brew "git-duet/tap/git-duet"
brew "heroku/brew/heroku"
brew "minifast/setup/dock-settings"
brew "minifast/setup/fast-key-repeat-rate"
brew "minifast/setup/function-keys"
brew "minifast/setup/menu-clock-format"

cask "1password"
cask "caffeine"
cask "chromedriver"
cask "figma"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "krisp"
cask "ngrok"
cask "rowanj-gitx"
cask "sublime-text"
cask "utc-menu-clock"
cask "minifast/setup/git-config"
cask "minifast/setup/git-duet-config"
cask "minifast/setup/inputrc"
cask "minifast/setup/iterm2-config"
cask "minifast/setup/mosaic"
cask "minifast/setup/shared-memory"
cask "minifast/setup/starship-config"
cask "minifast/setup/sublime-text-config"
cask "minifast/setup/zsh-config"
